services:
  db:
    image: postgres
    container_name: meetcode-postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: chickenjockey
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - meetcode-network

# Backend-http used to be here too

  backend: #-https:
    build:
      context: ./backend
    container_name: meetcode-backend-https
    restart: always
    ports:
      #- "8001:8001"
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env.runtime
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://backend:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    entrypoint: ["./entrypoint.sh"]

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env.runtime
    container_name: meetcode-frontend
    restart: always
    ports:
      - "3000:3000"  # Adjust port as needed for your frontend
    depends_on:
      - backend

volumes:
  postgres_data:
